apiVersion: v1
kind: Service
metadata:
  name: backend-service # Used in frontend API_URL
spec:
  type: ClusterIP # Only accessible within the cluster
  selector:
    app: backend # Matches labels in backend-deployment
  ports:
  - protocol: TCP
    port: 8000 # Service listens on port 8000
    targetPort: 8000 # Pod listens on port 8000