# backend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      serviceAccountName: backend-ksa
      containers:
      - name: backend-app
        image: us-central1-docker.pkg.dev/parlay-and-pray-app/mlops-dream11-repo/backend-app:v3
        ports:
        - containerPort: 8000
        env:
        - name: GEMINI_API_KEY
          valueFrom:           
            secretKeyRef:      
              name: gemini-api-key-secret
              key: api_key               
        resources:
          requests:
            cpu: "500m"
            memory: "1Gi"
          limits:
             cpu: "1000m"
             memory: "2Gi"