# frontend-deployment.yaml (Updated)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      serviceAccountName: backend-ksa # Use the same KSA as the backend
      containers:
      - name: frontend-app
        image: us-central1-docker.pkg.dev/parlay-and-pray-app/mlops-dream11-repo/frontend-app:v4
        ports:
        - containerPort: 8501 # Streamlit default port
        env:
        - name: API_URL # Existing variable for prediction endpoint
          value: "http://backend-service.default.svc.cluster.local:8000/predict_team/"
        - name: CHAT_API_URL # New variable for chat endpoint
          value: "http://backend-service.default.svc.cluster.local:8000/chat/"
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"