apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: LoadBalancer # Exposes the service externally
  selector:
    app: frontend # Matches labels in frontend-deployment
  ports:
  - protocol: TCP
    port: 80 # Load Balancer listens on port 80 (standard HTTP)
    targetPort: 8501 # Pod listens on port 8501 (Streamlit)