apiVersion: apps/v1
kind: Deployment
metadata:
  name: metaflow-service
  labels:
    app: metaflow-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metaflow-service
  template:
    metadata:
      labels:
        app: metaflow-service
    spec:
      containers:
      - name: metaflow-service
        image: us-central1-docker.pkg.dev/parlay-and-pray-app/mlops-dream11-repo/metaflow-metadata-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /ping
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ping
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: metaflow-service
  labels:
    app: metaflow-service
spec:
  type: LoadBalancer
  selector:
    app: metaflow-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080