name: Deploy Backend to Cloud Run

on:
  push:
    branches: [master]

env:
  PROJECT_ID: mlops-dream11
  REGION: us-west2
  SERVICE_NAME: mlflow-run
  IMAGE_TAG: v1
  ARTIFACT_REPO: mlops-dream11-repo
  ARTIFACT_URL: us-west2-docker.pkg.dev/mlops-dream11/mlops-dream11-repo/mlflow:v1

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker and gcloud
      run: |
        echo "${{ secrets.GCP_DEPLOY_KEY }}" > deploy-key.json
        gcloud auth activate-service-account --key-file=deploy-key.json
        gcloud config set project $PROJECT_ID
        gcloud auth configure-docker $REGION-docker.pkg.dev

    - name: Build Docker image
      run: |
        docker build --platform linux/amd64 -t $ARTIFACT_URL ./src/backend

    - name: Push Docker image to Artifact Registry
      run: |
        docker push $ARTIFACT_URL

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy $SERVICE_NAME \
          --image $ARTIFACT_URL \
          --region $REGION \
          --service-account mlops-dream11-sa@$PROJECT_ID.iam.gserviceaccount.com \
          --update-secrets=/secrets/credentials=access_keys:latest \
          --update-secrets=POSTGRESQL_URL=database_url:latest \
          --update-secrets=STORAGE_URL=bucket_url:latest \
          --memory 2Gi \
          --allow-unauthenticated \
          --port 8080
