name: MLflow Training + Logging

on:
  push:
    branches: [master]

env:
  MLFLOW_TRACKING_URI: https://mlflow-run-337769530755.us-west2.run.app
  GOOGLE_APPLICATION_CREDENTIALS: mlflow-key.json

jobs:
  mlflow-training:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r src/backend/requirements.txt

    - name: Set up MLflow key
      run: |
        echo "${{ secrets.GCP_MLFLOW_KEY }}" > mlflow-key.json

    - name: Run MLflow training script
      run: |
        python src/backend/training.py
